stages:
  - build_stage
  - deploy_stage

build:
  stage: build_stage
  image: node:14 
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
      - package-lock.json
  cache:
    paths:
      - node_modules

deploy:
  stage: deploy_stage
  image: node:14 
  script:
    - npm install 
    - npm start 
